# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/daantje/Downloads/Linux_Unreal_Engine_5.7.4

TARGETS = \
	ProjectPublish-Android-DebugGame  \
	ProjectPublish-Android-Development  \
	ProjectPublish-Android-Shipping  \
	ProjectPublish-Linux-DebugGame  \
	ProjectPublish-Linux-Development  \
	ProjectPublish-Linux-Shipping  \
	ProjectPublish-LinuxArm64-DebugGame  \
	ProjectPublish-LinuxArm64-Development  \
	ProjectPublish-LinuxArm64-Shipping  \
	ProjectPublish \
	ProjectPublishEditor-Linux-DebugGame  \
	ProjectPublishEditor-Linux-Development  \
	ProjectPublishEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ProjectPublishEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ProjectPublishEditor-Linux-Debug


ProjectPublish-Android-DebugGame:
	 $(BUILD) ProjectPublish Android DebugGame  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-Android-Development:
	 $(BUILD) ProjectPublish Android Development  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-Android-Shipping:
	 $(BUILD) ProjectPublish Android Shipping  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-Linux-DebugGame:
	 $(BUILD) ProjectPublish Linux DebugGame  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-Linux-Development:
	 $(BUILD) ProjectPublish Linux Development  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-Linux-Shipping:
	 $(BUILD) ProjectPublish Linux Shipping  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-LinuxArm64-DebugGame:
	 $(BUILD) ProjectPublish LinuxArm64 DebugGame  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-LinuxArm64-Development:
	 $(BUILD) ProjectPublish LinuxArm64 Development  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish-LinuxArm64-Shipping:
	 $(BUILD) ProjectPublish LinuxArm64 Shipping  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublish: ProjectPublish-Linux-Development

ProjectPublishEditor-Linux-DebugGame:
	 $(BUILD) ProjectPublishEditor Linux DebugGame  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublishEditor-Linux-Development:
	 $(BUILD) ProjectPublishEditor Linux Development  -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" $(ARGS)

ProjectPublishEditor: ProjectPublishEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/daantje/Documents/SchoolProjecten/Project-publish/ProjectPublish.uproject" -Game 

.PHONY: $(TARGETS)
